### ISSUE TITLE
Error while compile application

### ISSUE THREAD

**Issue by Bes79** [Mastersam07/fIconsax#8]
Font asset "IconsaxOutline.ttf" was tree-shaken, reducing it from 355068 to 351032 bytes (1.1% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when
building your app.

**Comment by Mastersam07** [comment]
That's not an error. The tree-shaking process reduced the size of the "IconsaxOutline.ttf" font asset in your app by removing unused icons, resulting in a slight decrease in file size.
